### PR TITLE
(52) Fix background alignment

### PR DESCRIPTION
**Pull request by pezholio**
This fixes the background alignment, which looks odd when the cookie banner is visible, and applies some more modern CSS tactics and png transparency

### Before

image

### After
image

### CODE REVIEW

**Comment by CristinaRO** [comment]
Er, are the "naked" FAQ and Leaderboard menu items a side effect of this change?

**Comment by pezholio** [comment]
Oh no, this is something weird going on with my dev environment. Lemme do a new screenshot

**Comment by CristinaRO** [comment]
[Bug (desktop): background gradient becomes misaligned when the cookie banner is showing](https://trello.com/c/WeNm6dOc/52-bug-desktop-background-gradient-becomes-misaligned-when-the-cookie-banner-is-showing)

**Comment by CristinaRO** [comment]
@pezholio Something weird is happening in all my browsers. Attached is the Firefox version, but they're all doing it 😬 

Screenshot 2022-05-03 at 16 51 23

**Comment by pezholio** [comment]
@CristinaRO Oh, I see what's happening. I've added `background-attachment: fixed;`, which should fix it 👍

**Review by CristinaRO — APPROVED** [review]
👍🏻

**Pull request merged**
