### PR TITLE
Cookie banner design

### PR DESCRIPTION
**Pull request by CristinaRO**
## Changes in this PR
- Implement cookie banner improvements in line with the design

### Before
Screenshot 2022-06-20 at 16 05 37

### After
Screenshot 2022-06-20 at 16 06 24

### CODE REVIEW

**Comment by CristinaRO** [comment]
[Implement the cookie banner design](https://trello.com/c/oTUCuWRb/99-implement-the-cookie-banner-design)

**Comment by lewisnyman** [comment]
Normal
Screenshot 2022-08-23 at 14 54 54

Hover
Screenshot 2022-08-23 at 14 55 07

Focus
Screenshot 2022-08-23 at 14 55 18

Active
Screenshot 2022-08-23 at 14 55 27

**Review by erbridge — COMMENTED** [review]
@CristinaRO Is there anything you're aware of (as the original author) that might make this not ok to merge?

**Comment by CristinaRO** [comment]
> @CristinaRO Is there anything you're aware of (as the original author) that might make this not ok to merge?

If it's been reviewed by someone who is more confident with CSS than me, then no. (This was my learning ground for `flex`.)

**Review by erbridge — APPROVED** [review]

**Pull request merged**
