### PR TITLE
Various style tweaks

### PR DESCRIPTION
**Pull request by CristinaRO**
## Changes in this PR
- Change title text in <head> to "ScenicOrNot" for consistency with rest of current site
- On desktop, in text under photo: make "by" and parentheses white
- On the leaderboard, make "Top 5" and "Bottom 5" bold on mobile too
- Change favicon
- Make full stop after "Warwick Business School" white

### CODE REVIEW

**Comment by CristinaRO** [comment]
[On desktop, in text under photo: make "by" and parentheses white](https://trello.com/c/VoZibkSG/59-on-desktop-in-text-under-photo-make-by-and-parentheses-white)

**Comment by CristinaRO** [comment]
[Change title text in <head> to "ScenicOrNot" for consistency with rest of current site](https://trello.com/c/do7bRrVv/64-change-title-text-in-head-to-scenicornot-for-consistency-with-rest-of-current-site)

**Comment by CristinaRO** [comment]
[On the leaderboard, make "Top 5" and "Bottom 5" bold on mobile too](https://trello.com/c/Ls41w5HD/77-on-the-leaderboard-make-top-5-and-bottom-5-bold-on-mobile-too)

**Comment by CristinaRO** [comment]
[Change favicon](https://trello.com/c/mqHVAImW/55-change-favicon)

**Review by pezholio — COMMENTED** [review]
It might make sense to have something a bit more related to the site as the favicon. The one that's replaced the dxw logo is the same as the mySociety one (which I think is legacy from when the site was controlled by mySociety). Happy to knock something up 👍

**Review by pezholio — APPROVED** [review]

**Pull request merged**
